### ISSUE TITLE
Code not executed, timing inaccurate?

### ISSUE THREAD

**Issue by moshemalawach** [Mec-iS/rust-wasm-python-101#3]
Code isn't actually executed, you need to change the outside parenthesis in the timeit calls to brakets.

Example:
t_py = timeit.timeit('(py_simple_add(n-1, n) for n in range(100, 1000))', number=10000)

Becomes:
t_py = timeit.timeit('[py_simple_add(n-1, n) for n in range(100, 1000)]', number=10000)

And this way you see that the code isn't actually executed at all, as the functions aren't available in the timeit context.

**Comment by Mec-iS** [comment]
Yes thanks, I am still working on the timing module. Will make a PR soon with the right code.

**Comment by Mec-iS** [comment]
I took some time to make things work: 988e9711576e04cbb54a331f9f72d5cffc567cdb
thanks

**Comment by Mec-iS** [comment]
Please double-check my results:
```
    py add 1.269273363001048
    t_wasm add 8.957978017999267
    py fibo 43.752940606000266
    t_wasm fibo 1.2281139650003752
    py shapely convex hull 48.14261505699869
    t_wasm rust-geo convex hull 2.3167089839989785
```
